wallpaper {
    monitor = eDP-1
    path = /home/user/Archieve/Media/Wallpapers/Day&Night/abstract/contents/images_dark/3840x2160.jpg
    fit_mode = contain
}

wallpaper {
    monitor = HDMI-A-3
    path = /home/user/Archieve/Media/Wallpapers/Day&Night/abstract/contents/images_dark/3840x2160.jpg
    fit_mode = contain
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/user/Archieve/Media/Wallpapers/Day&Night/abstract/contents/images_dark/3840x2160.jpg
    fit_mode = contain
}
